### ISSUE TITLE
Message payload always ends with 16 NULL characters

### ISSUE THREAD

**Issue by githubaccount624** [pimeys/rust-web-push#16]
Hi again,

Just finishing getting things set up and not sure if I found a bug or if I'm doing something wrong. I'm sending a push notification but the contents being received from the browser have some extraneous data. That is, it seems as if the data payload ends with 16 NULL characters (regardless of payload length).

This normally wouldn't be a problem but it's causing the `event.data.json()` function to error out on the frontend because it fails to parse the data payload due to these characters at the end and it's causing me to get the error `Unexpected token   in JSON at position 127`

At first I thought they were whitespace characters, but then I did `console.log(event.data.arrayBuffer());` and found out that the array always ended with 16 instances of `0`.

[Here's a picture of the end of the array](https://i.imgur.com/6K1cxVL.png)

Just to be sure I wasn't sending this array myself I did a `println!` on my Rust server. Here's the code:

```rust
async fn send_push_notification(subscription_info: SubscriptionInfo, message: &str, web_push_client: &WebPushClient, client: &Client) -> Result<(), GenericDBError> {
    let mut sig_builder = VapidSignatureBuilder::from_pem(keys::NOTIFICATIONS_PRIVATE_KEY, &subscription_info)?;
    sig_builder.add_claim("sub", "mailto:test@example.com"); // needed?
    
    let signature = sig_builder.build()?;

    let mut builder = WebPushMessageBuilder::new(&subscription_info)?;

    builder.set_payload(ContentEncoding::AesGcm, message.as_bytes());
    builder.set_vapid_signature(signature);
    builder.set_ttl(2_419_200); // 4 weeks

    println!("payload: {:?}", message.as_bytes());

    web_push_client.send(builder.build()?).await?;

    Ok(())
}
```

And sure enough there weren't any zeroes at the end of that array, so I don't _think_ I'm doing anything wrong, but not sure.

I was looking through the source code for the number 16, and I saw [here](https://github.com/pimeys/rust-web-push/blob/master/src/http_ece.rs#L107) that there are 16 bytes for the salt. Maybe it's related to that? Actually, there's several instances in that file of the number 16.. `max_payload` minuses 16 at the end, salt_bytes is 16 bytes, EceKey is given the number 16 as a parameter, etc.

I can bandaid fix this on the frontend by doing this, but obviously I do not want to do this lol:

```javascript
  var enc = new TextDecoder("utf-8");
  let arr = new Uint8Array(event.data.arrayBuffer()).filter(x => x !== 0);
  let data = JSON.parse(enc.decode(arr));
```

**Comment by pimeys** [comment]
Ha. So that was the extended payload. The switch from arrays to vectors didn't go that cleanly then...

**Comment by pimeys** [comment]
But also the payload is zero-padded as per standard to make all payloads the same size and not leak the length of the message. Don't know enough of the JavaScript to see if you do something wrong in there...

**Comment by githubaccount624** [comment]
Hey sorry I fell asleep.

I still _think_ it's a bug for these reasons:

1) All the tutorials I'm reading on push notifications say you should just be able to call `event.data.json()` on it. Here's a quote from the google docs: `When we receive a push notification with a payload, the data is available directly on the event object. This data can be of any type, and you can access the data as a JSON result, a BLOB, a typed array, or raw text.` Currently this errors out because of the presence of the 16 NULL characters at the end of the payload.

2) I'm also not sure what you mean by all the payloads being the same size. The ones I'm receiving are all different sizes (makes sense because some messages are longer than others)

3) I don't think I'm doing anything wrong in JavaScript, because the entirety of my code at the moment is something like this in a service worker:

    self.addEventListener('push', function(event) {
        console.log(event.data.json());
    }

And that errors out due to the presence of the NULLs at the end of the payload. So it's basically a minimally reproduced case as is.

**Comment by pimeys** [comment]
Ugh, this is really hard to fix without a proper test setup (which I don't really want to build :D). Try out this branch if it fixes the problem for you:

https://github.com/pimeys/rust-web-push/pull/17

So what I think happens here is the change in the aead sealing. Before we were able to use a constant-size array for the payload and just write our data into it. Now Ring forces us to use a vector and what we know about vectors is you can extend them. So before we had the last 16 bytes reseved for the aead tag (which is in our case empty, meaning zeroes) and which should take an extra 16 bytes of space in the end.

Now with the old code, the last 16 bytes of the payload were reseved for the tag and never used due to tag being empty. In the current code we still reserve the last 16 bytes for the tag, but the ring function extends another 16 bytes from the end of the payload for the tag (again zeroes).

Now I just cut the payload size with 16 bytes, pad the actual data exactly to the end of the payload and let the aead function to add the empty 16 bytes of data when signing. Seems like we get quite good test run with this, but I'd be happy for actual real world tests.

**Comment by githubaccount624** [comment]
Hooray, it's fixed! Thanks so much!
